[project]
name = "orangescogs"
version = "0.1.0"
description = "Utility cogs for tgstation codebases"
readme = "README.md"
requires-python = ">=3.11,<3.12"
license = "MIT"
authors = [
	{ name = "oranges", email = "email@oranges.net.nz" },
	{ name = "crossedfall" },
	{ name = "Will Roberts" },
]
maintainers = [{ name = "oranges", email = "email@oranges.net.nz" }]

[dependency-groups]
dev = [
	"Red-DiscordBot>=3,<4",
	"requests>=2.31.0,<3",
	"fuzzywuzzy>=0.18.0,<0.19",
	"tomlkit>=0.13.2,<0.14",
]

[tool.uv]
default-groups = ["dev"]
